### ISSUE TITLE
custom for OPi3LTS

### ISSUE THREAD

**Issue by 3Shoka** [nopnop2002/webioOP#4]
https://github.com/nopnop2002/webioOP/blob/bd49421bc2165f258f7a2084c52ef936eb87c6ad/webioOP-Zero.py#L11

how can I custom those pins as gpio in opi3lts ?

**Comment by nopnop2002** [comment]
[Wiring Pi-Python] needs to work on OPI3-LST.

I don't know because I don't have OPI3-LST.

**Comment by 3Shoka** [comment]
may be this link can help, https://github.com/orangepi-xunlong/wiringOP

I've seen your post on the orangepi forum, to change the BOARD and BCM binding configuration, but I forgot the topic and haven't found the link.
I want to ask, how is the calculation for bcm and board bindings?

**Comment by nopnop2002** [comment]
>how is the calculation for bcm and board bindings?

What is bcm?
What is board?

I also forgot the topic on the orangepi forum.

---
>may be this link can help, https://github.com/orangepi-xunlong/wiringOP

Perhaps you can use this information to create a [Wiring Pi-Python] that runs on OPI3-LST.

**Comment by 3Shoka** [comment]
sorry maybe this is out of topic,
from this http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=3194
how you determine pin map **Physical pin to actual GPIO pin** (BOARD) and **BCM pin to actual GPIO pin** (BCM)
I want to remap this to opi3lts pin

**Comment by nopnop2002** [comment]
>sorry maybe this is out of topic,

Don't care.

I forgot the contents.
I need time to think.

**Comment by nopnop2002** [comment]
_pin_map is Physical pin position & GPIO number.

```
Orange Pi Zero/R1

 +------+-----+----------+------+---+  OPi H2  +---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 |      |     |     3.3V |      |   |  1 || 2  |   |      | 5V       |     |      |
 |   12 |   0 |    SDA.0 | ALT2 | 0 |  3 || 4  |   |      | 5V       |     |      |
 |   11 |   1 |    SCL.0 | ALT2 | 0 |  5 || 6  |   |      | GND      |     |      |
 |    6 |   2 |    PWM.1 |  OFF | 0 |  7 || 8  | 0 | ALT2 | TXD.1    | 3   | 198  |
 |      |     |      GND |      |   |  9 || 10 | 0 | ALT2 | RXD.1    | 4   | 199  |
 |    1 |   5 |    RXD.2 | ALT2 | 0 | 11 || 12 | 0 | OFF  | PA07     | 6   | 7    |
 |    0 |   7 |    TXD.2 | ALT2 | 0 | 13 || 14 |   |      | GND      |     |      |
 |    3 |   8 |    CTS.2 |  OFF | 0 | 15 || 16 | 0 | ALT3 | SDA.1    | 9   | 19   |
 |      |     |     3.3V |      |   | 17 || 18 | 0 | ALT3 | SCK.1    | 10  | 18   |
 |   15 |  11 |   MOSI.1 | ALT2 | 1 | 19 || 20 |   |      | GND      |     |      |
 |   16 |  12 |   MISO.1 | ALT2 | 0 | 21 || 22 | 0 | OFF  | RTS.2    | 13  | 2    |
 |   14 |  14 |   SCLK.1 | ALT2 | 0 | 23 || 24 | 0 | ALT2 | CE.1     | 15  | 13   |
 |      |     |      GND |      |   | 25 || 26 | 0 | OFF  | PA10     | 16  | 10   |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+  OPi H2  +---+------+----------+-----+------+

_pin_map = {
    # Physical pin to actual GPIO pin
    BOARD: {
        3: 12,
        5: 11,
        7: 6,
        8: 198,
        10: 199,
        11: 1,
        12: 7,
        13: 0,
        15: 3,
        16: 19,
        18: 18,
        19: 15,
        21: 16,
        22: 2,
        23: 14,
        24: 13,
        26: 10
    },
```

This library already seems to support Orange-PI3.

https://github.com/rm-hull/OPi.GPIO

https://github.com/rm-hull/OPi.GPIO/blob/master/orangepi/pi3.py


------


webioOP uses [Wiring Pi-Python] instead of [OPi.GPIO].

So you need to change to use [OPi.GPIO].


I remember that OPi.GPIO could not get the current state of GPIO.
The current state of GPIO is one of the following, called Mode or ALT Mode.
This is an alternative mode.

```
ALTS = [
   "IN", "OUT", "ALT5", "ALT4", "ALT0", "ALT1", "ALT2", "ALT3"
   ]
```

wiringpi can get the current alternative mode.

https://github.com/nopnop2002/webioOP/blob/master/webioOP.py#L49

https://github.com/nopnop2002/webioOP/blob/master/webioOP.py#L53

**Comment by 3Shoka** [comment]
> This library already seems to support Orange-PI3.
> https://github.com/rm-hull/OPi.GPIO
> https://github.com/rm-hull/OPi.GPIO/blob/master/orangepi/pi3.py

thanks for this reference, I didn't notice that

so when I have installed WiringOP, I just need to remap the pin to opi 3, right ?

thanks

**Comment by nopnop2002** [comment]
>so when I have installed WiringOP, I just need to remap the pin to opi 3, right ?


Yes, that's right.


Please publish when WiringOP for OPI3 is completed.

**Comment by nopnop2002** [comment]
I completely rewrote it.
I don't have OPI3, but I confirmed with LITE2.
Please try with the latest version.

**Comment by 3Shoka** [comment]
thanks, i appreciate that
I will try it later


I have my own version here for my opi 3
https://github.com/3Shoka/webioOP/blob/master/webioOP-Pi3.py
I don't know is it correct or not, but it works for me

**Comment by nopnop2002** [comment]
My repository probably works with all Orange Pi series.

Have a nice day.

**Comment by 3Shoka** [comment]
got error : 
```
sudo python3 ./gpio_test.py
Traceback (most recent call last):
  File "./gpio_test.py", line 2, in <module>
    import gpio
ImportError: /usr/local/lib/libwiringPi.so: undefined symbol: crypt
```

am I missing something ?

**Comment by nopnop2002** [comment]
Please tell me the result.
```
$ python3 -m pip list -l | grep Gpio
GpioMethod          1.0
```

**Comment by 3Shoka** [comment]
the result is same as you
`GpioMethod          1.0`

**Comment by nopnop2002** [comment]
I don't know the reason.

This is my result.

```
$ sudo python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpio
```

**Comment by 3Shoka** [comment]
```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/libwiringPi.so: undefined symbol: crypt
```

do I need to install wiringOP-Python first ?

**Comment by nopnop2002** [comment]
>do I need to install wiringOP-Python first ?


No.


This repository no longer uses wiringOP-Python.


Only using WiringOP library provided by xunlong.

**Comment by nopnop2002** [comment]
Does this work?

```
$ gpio readall
 +------+-----+----------+------+---+  OPi H6  +---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 |      |     |     3.3V |      |   |  1 || 2  |   |      | 5V       |     |      |
 |  230 |   0 |    SDA.1 |  OUT | 0 |  3 || 4  |   |      | 5V       |     |      |
 |  229 |   1 |    SCL.1 | ALT4 | 0 |  5 || 6  |   |      | GND      |     |      |
 |  228 |   2 |      PH4 |  OFF | 0 |  7 || 8  | 0 | OFF  | PD21     | 3   | 117  |
 |      |     |      GND |      |   |  9 || 10 | 0 | OFF  | PD22     | 4   | 118  |
 |  120 |   5 |    RXD.3 | ALT2 | 0 | 11 || 12 | 0 | OFF  | PC9      | 6   | 73   |
 |  119 |   7 |    TXD.3 | ALT2 | 0 | 13 || 14 |   |      | GND      |     |      |
 |  122 |   8 |    CTS.3 | ALT2 | 0 | 15 || 16 | 0 | OFF  | PC8      | 9   | 72   |
 |      |     |     3.3V |      |   | 17 || 18 | 0 | OFF  | PC7      | 10  | 71   |
 |   66 |  11 |   MOSI.0 |  OFF | 0 | 19 || 20 |   |      | GND      |     |      |
 |   67 |  12 |   MISO.0 |  OFF | 0 | 21 || 22 | 0 | ALT2 | RTS.3    | 13  | 121  |
 |   64 |  14 |   SCLK.0 |  OFF | 0 | 23 || 24 | 0 | OFF  | CE.0     | 15  | 69   |
 |      |     |      GND |      |   | 25 || 26 | 0 | OFF  | PH3      | 16  | 227  |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+  OPi H6  +---+------+----------+-----+------+
```

**Comment by 3Shoka** [comment]
yes,
```
> gpio readall
 +------+-----+----------+------+---+   OPi 3  +---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 |      |     |     3.3V |      |   |  1 || 2  |   |      | 5V       |     |      |
 |  122 |   0 |    SDA.0 |  OFF | 0 |  3 || 4  |   |      | 5V       |     |      |
 |  121 |   1 |    SCL.0 |  OFF | 0 |  5 || 6  |   |      | GND      |     |      |
 |  118 |   2 |    PWM.0 |  OFF | 0 |  7 || 8  | 0 | OFF  | PL02     | 3   | 354  |
 |      |     |      GND |      |   |  9 || 10 | 0 | OFF  | PL03     | 4   | 355  |
 |  120 |   5 |    RXD.3 | ALT4 | 0 | 11 || 12 | 0 | OFF  | PD18     | 6   | 114  |
 |  119 |   7 |    TXD.3 | ALT4 | 0 | 13 || 14 |   |      | GND      |     |      |
 |  362 |   8 |     PL10 |  OFF | 0 | 15 || 16 | 0 | OFF  | PD15     | 9   | 111  |
 |      |     |     3.3V |      |   | 17 || 18 | 0 | OFF  | PD16     | 10  | 112  |
 |  229 |  11 |   MOSI.1 | ALT2 | 0 | 19 || 20 |   |      | GND      |     |      |
 |  230 |  12 |   MISO.1 | ALT2 | 0 | 21 || 22 | 0 | OFF  | PD21     | 13  | 117  |
 |  228 |  14 |   SCLK.1 | ALT2 | 0 | 23 || 24 | 0 | ALT2 | CE.1     | 15  | 227  |
 |      |     |      GND |      |   | 25 || 26 | 0 | OFF  | PL08     | 16  | 360  |
 +------+-----+----------+------+---+----++----+---+------+----------+-----+------+
 | GPIO | wPi |   Name   | Mode | V | Physical | V | Mode | Name     | wPi | GPIO |
 +------+-----+----------+------+---+   OPi 3  +---+------+----------+-----+------+
```

**Comment by nopnop2002** [comment]
Thnak you.

I need some time.

**Comment by nopnop2002** [comment]
I just did a clean install of the latest armbian.

I think the armbian standard python is still Python 3.7.3.
```
$ uname -a
Linux orangepipc 5.15.25-sunxi #22.02.1 SMP Sun Feb 27 09:23:25 UTC 2022 armv7l GNU/Linux

$ python3 --version
Python 3.7.3
```


Your python is Python 3.8.10.
```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
```

Did you add this?

**Comment by 3Shoka** [comment]
I'm using ubuntu server provide by orange pi, from [orangepi](http://www.orangepi.org/downloadresources/) 
```
> uname -a
Linux orangepi3-lts 4.9.118-sun50iw6 #52 SMP PREEMPT Thu Dec 30 10:47:10 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by nopnop2002** [comment]
Thank you.

I updated from buster to bullseye.


I have the same problem.

```
$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/libwiringPi.so: undefined symbol: crypt
```

**Comment by nopnop2002** [comment]
A short break....

**Comment by nopnop2002** [comment]
There is no solution hint anywhere.

There is no doubt that it is due to the version of python.

**Comment by 3Shoka** [comment]
its okay, maybe should use wiringOP python 
or downgrade to python 3.7

**Comment by nopnop2002** [comment]
I looking for a workaround.


I can't find the any hint.

This is rare.

may be give up.

----

Thank you for your cooperation.

**Comment by nopnop2002** [comment]
I tried it with something other than buster, but it doesn't work.

It depends on the generated SO library, not the Python version.

https://github.com/nopnop2002/webioOP/issues/5

I don't know the workaround.
